services:
  api:
    image: fastapi-app:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
