services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    volumes:
      - .:/app
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis

  celery_beat:
    build: .
    volumes:
      - .:/app
    command: celery -A celery_app beat --loglevel=info
    depends_on:
      - redis
