services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    networks:
      - shared_network_prod
      ipv4_address: 172.20.0.10

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network_prod
      ipv4_address: 172.20.0.11

networks:
  shared_network_prod:
    external:
      name: shared_network_prod
