services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
