"""update tratment_menu add uniq index2

Revision ID: 07500f851182
Revises: 0dfabedf0641
Create Date: 2025-05-15 16:18:26.134509

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07500f851182"
down_revision: Union[str, None] = "0dfabedf0641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_treatment_menu_name", table_name="treatment_menu")
    op.create_unique_constraint(
        "uq_treatment_menu_shop_id_name", "treatment_menu", ["shop_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_treatment_menu_shop_id_name", "treatment_menu", type_="unique"
    )
    op.create_index("uq_treatment_menu_name", "treatment_menu", ["name"], unique=True)
    # ### end Alembic commands ###
