"""delete phonebook model: delete unq index

Revision ID: 0b6d99f6fb6b
Revises: 07500f851182
Create Date: 2025-05-17 18:55:23.233420

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b6d99f6fb6b"
down_revision: str | None = "07500f851182"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_shop_phone_deleted", table_name="phonebook")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_shop_phone_deleted",
        "phonebook",
        ["shop_id", "phone_number", "deleted_at"],
        unique=True,
    )
    # ### end Alembic commands ###
