"""update tratment_menu add uniq index

Revision ID: 0dfabedf0641
Revises: 294bb1eb9147
Create Date: 2025-05-15 16:15:43.225272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfabedf0641'
down_revision: Union[str, None] = '294bb1eb9147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_treatment_menu_name', 'treatment_menu', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_treatment_menu_name', 'treatment_menu', type_='unique')
    # ### end Alembic commands ###
