"""update treatment add customer fields and make phonebook_id nullable with indexes

Revision ID: 1e1480804309
Revises: 311e5e0e6ce1
Create Date: 2025-10-10 17:24:33.520303

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e1480804309"
down_revision: str | None = "311e5e0e6ce1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "treatment",
        sa.Column(
            "customer_name", sa.String(length=100), nullable=True, comment="고객명"
        ),
    )
    op.add_column(
        "treatment",
        sa.Column(
            "customer_phone",
            sa.String(length=20),
            nullable=True,
            comment="고객 전화번호",
        ),
    )
    op.alter_column(
        "treatment",
        "phonebook_id",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
        existing_comment="시술 대상 고객 ID",
    )
    op.create_index(
        "idx_treatment_shop_phone",
        "treatment",
        ["shop_id", "customer_phone"],
        unique=False,
    )
    op.create_index(
        "idx_treatment_shop_reserved",
        "treatment",
        ["shop_id", "reserved_at"],
        unique=False,
    )
    op.create_index(
        "idx_treatment_shop_status",
        "treatment",
        ["shop_id", "status", "reserved_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_treatment_phonebook_id"), "treatment", ["phonebook_id"], unique=False
    )
    op.create_index(
        op.f("ix_treatment_shop_id"), "treatment", ["shop_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_treatment_shop_id"), table_name="treatment")
    op.drop_index(op.f("ix_treatment_phonebook_id"), table_name="treatment")
    op.drop_index("idx_treatment_shop_status", table_name="treatment")
    op.drop_index("idx_treatment_shop_reserved", table_name="treatment")
    op.drop_index("idx_treatment_shop_phone", table_name="treatment")
    op.alter_column(
        "treatment",
        "phonebook_id",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
        existing_comment="시술 대상 고객 ID",
    )
    op.drop_column("treatment", "customer_phone")
    op.drop_column("treatment", "customer_name")
    # ### end Alembic commands ###
