"""remove total_price treatment

Revision ID: 26c3cb6bca80
Revises: 5b57aeb86c24
Create Date: 2025-04-21 13:55:14.193007

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26c3cb6bca80"
down_revision: Union[str, None] = "5b57aeb86c24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("treatment", "total_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "treatment",
        sa.Column(
            "total_price",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="총 실제 시술 가격",
        ),
    )
    # ### end Alembic commands ###
