"""update phonebook model: index

Revision ID: 294bb1eb9147
Revises: 79b4cd42a475
Create Date: 2025-05-14 16:29:55.187889

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "294bb1eb9147"
down_revision: str | None = "79b4cd42a475"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_phonebook_id", table_name="phonebook")
    op.create_index(
        "idx_shop_deleted_group",
        "phonebook",
        ["shop_id", "deleted_at", "group_name"],
        unique=False,
    )
    op.create_index(
        "idx_shop_deleted_name",
        "phonebook",
        ["shop_id", "deleted_at", "name"],
        unique=False,
    )
    op.create_index(
        "idx_shop_deleted_phone",
        "phonebook",
        ["shop_id", "deleted_at", "phone_number"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_shop_phone_deleted", "phonebook", ["shop_id", "phone_number", "deleted_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_shop_phone_deleted", "phonebook", type_="unique")
    op.drop_index("idx_shop_deleted_phone", table_name="phonebook")
    op.drop_index("idx_shop_deleted_name", table_name="phonebook")
    op.drop_index("idx_shop_deleted_group", table_name="phonebook")
    op.create_index("ix_phonebook_id", "phonebook", ["id"], unique=False)
    # ### end Alembic commands ###
