"""create table DevicePushToken

Revision ID: 311e5e0e6ce1
Revises: 47a0a034caff
Create Date: 2025-09-17 18:06:53.033554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311e5e0e6ce1'
down_revision: Union[str, None] = '47a0a034caff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='디바이스 푸시 토큰 ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='유저 ID'),
    sa.Column('shop_id', sa.Integer(), nullable=True, comment='샵 ID'),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='디바이스 고유 ID'),
    sa.Column('token', sa.Text(), nullable=False, comment='FCM 토큰'),
    sa.Column('platform', sa.String(length=10), nullable=False, comment='플랫폼 (iOS/Android 등)'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='디바이스 푸시 토큰 테이블'
    )
    op.create_index(op.f('ix_device_push_tokens_device_id'), 'device_push_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_push_tokens_shop_id'), 'device_push_tokens', ['shop_id'], unique=False)
    op.create_index(op.f('ix_device_push_tokens_token'), 'device_push_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_push_tokens_user_id'), 'device_push_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_push_tokens_user_id'), table_name='device_push_tokens')
    op.drop_index(op.f('ix_device_push_tokens_token'), table_name='device_push_tokens')
    op.drop_index(op.f('ix_device_push_tokens_shop_id'), table_name='device_push_tokens')
    op.drop_index(op.f('ix_device_push_tokens_device_id'), table_name='device_push_tokens')
    op.drop_table('device_push_tokens')
    # ### end Alembic commands ###
