"""delete uniq index shop_invite

Revision ID: 40e91ecbe21e
Revises: 65e580727ffb
Create Date: 2025-05-22 17:16:05.904571

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40e91ecbe21e"
down_revision: str | None = "65e580727ffb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("shop_invite_ibfk_1", "shop_invite", type_="foreignkey")
    op.drop_index("uq_shop_invite", table_name="shop_invite")
    op.create_foreign_key(
        "fk_shop_invite_shop_id",
        "shop_invite",
        "shop",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_shop_invite_shop_id", "shop_invite", type_="foreignkey")
    op.create_index(
        "uq_shop_invite", "shop_invite", ["shop_id", "invite_code"], unique=True
    )
    op.create_foreign_key(
        "shop_invite_ibfk_1",
        "shop_invite",
        "shop",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
