"""add colum trement_item

Revision ID: 5540e5174e50
Revises: ca9537ba4378
Create Date: 2025-04-14 20:24:06.793691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5540e5174e50'
down_revision: Union[str, None] = 'ca9537ba4378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_item', sa.Column('baisc_price', sa.Integer(), server_default='0', nullable=False, comment='기본 가격'))
    op.add_column('treatment_item', sa.Column('duration_minute', sa.Integer(), server_default='0', nullable=False, comment='소요 시간 (분)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_item', 'duration_minute')
    op.drop_column('treatment_item', 'baisc_price')
    # ### end Alembic commands ###
