"""update updated_at default time

Revision ID: 55b0f3aef89c
Revises: 64915ec62564
Create Date: 2025-04-16 11:09:20.607905

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55b0f3aef89c"
down_revision: str | None = "64915ec62564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phonebook",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일",
        existing_comment="수정일시",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "shop",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일",
        existing_comment="수정일시",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "treatment",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일",
        existing_comment="수정일시",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "treatment_menu",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일",
        existing_comment="수정일시",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "treatment_menu_detail",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일",
        existing_comment="수정일시",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "treatment_menu_detail",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일시",
        existing_comment="수정일",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "treatment_menu",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일시",
        existing_comment="수정일",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "treatment",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일시",
        existing_comment="수정일",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "shop",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일시",
        existing_comment="수정일",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "phonebook",
        "updated_at",
        existing_type=mysql.DATETIME(),
        comment="수정일시",
        existing_comment="수정일",
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    # ### end Alembic commands ###
