"""update phonebook model: add unique constraint

Revision ID: 583bca8862b2
Revises: ed729f7d29a6
Create Date: 2025-04-08 16:11:13.379893

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "583bca8862b2"
down_revision: Union[str, None] = "ed729f7d29a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_id_phone_number", "phonebook", ["user_id", "phone_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_id_phone_number", "phonebook", type_="unique")
    # ### end Alembic commands ###
