"""mod colum trement_item basic_price

Revision ID: 63f5c0e04e8e
Revises: 5540e5174e50
Create Date: 2025-04-14 20:30:30.708651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63f5c0e04e8e'
down_revision: Union[str, None] = '5540e5174e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_item', sa.Column('base_price', sa.Integer(), server_default='0', nullable=False, comment='기본 가격'))
    op.add_column('treatment_item', sa.Column('duration_min', sa.Integer(), server_default='0', nullable=False, comment='소요 시간 (분)'))
    op.drop_column('treatment_item', 'baisc_price')
    op.drop_column('treatment_item', 'duration_minute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_item', sa.Column('duration_minute', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='소요 시간 (분)'))
    op.add_column('treatment_item', sa.Column('baisc_price', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='기본 가격'))
    op.drop_column('treatment_item', 'duration_min')
    op.drop_column('treatment_item', 'base_price')
    # ### end Alembic commands ###
