"""remove refresh token table

Revision ID: 6496893a2eb5
Revises: fa22b5296fc2
Create Date: 2025-05-22 00:55:44.751575

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6496893a2eb5'
down_revision: Union[str, None] = 'fa22b5296fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='리프레시 토큰 ID'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='사용자 ID'),
    sa.Column('token', mysql.TEXT(), nullable=False, comment='리프레시 토큰'),
    sa.Column('expired_at', mysql.DATETIME(), nullable=False, comment='만료일시'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_refresh_tokens_id', 'refresh_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
