"""update shop_invite uniq

Revision ID: 65e580727ffb
Revises: a6c7166dbc9e
Create Date: 2025-05-22 15:58:53.736299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e580727ffb'
down_revision: Union[str, None] = 'a6c7166dbc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shop_invite', 'shop_invite', ['shop_id', 'invite_code'])
    op.create_table_comment(
        'shop_invite',
        '샵 초대코드 테이블',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'shop_invite',
        existing_comment='샵 초대코드 테이블',
        schema=None
    )
    op.drop_constraint('uq_shop_invite', 'shop_invite', type_='unique')
    # ### end Alembic commands ###
