"""update invite shop_id index

Revision ID: 7990f5c909da
Revises: d91be80d4079
Create Date: 2025-05-22 17:31:05.035416

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7990f5c909da"
down_revision: str | None = "d91be80d4079"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_shop_invite_shop_id", "shop_invite", type_="foreignkey")
    op.drop_index("uq_shop_invite_shop_id", table_name="shop_invite")
    op.create_index("idx_shop_invite_shop_id", "shop_invite", ["shop_id"], unique=False)
    op.create_foreign_key(
        "fk_shop_invite_shop_id",
        "shop_invite",
        "shop",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_shop_invite_shop_id", "shop_invite", type_="foreignkey")
    op.drop_index("idx_shop_invite_shop_id", table_name="shop_invite")
    op.create_index("uq_shop_invite_shop_id", "shop_invite", ["shop_id"], unique=True)
    op.create_foreign_key(
        "fk_shop_invite_shop_id",
        "shop_invite",
        "shop",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
