"""updated_at test

Revision ID: 79b4cd42a475
Revises: eee7baaeea97
Create Date: 2025-05-07 18:05:51.743814

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79b4cd42a475"
down_revision: str | None = "eee7baaeea97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "phonebook", "shop", ["shop_id"], ["id"], ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "phonebook", type_="foreignkey")
    # ### end Alembic commands ###
