"""update treatment model: phonebook_id

Revision ID: 7dfe484d30d3
Revises: dbd2afd7bc24
Create Date: 2025-04-08 19:45:20.629603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfe484d30d3'
down_revision: Union[str, None] = 'dbd2afd7bc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('phonebook_id', sa.Integer(), nullable=False, comment='시술 대상 고객 ID'))
    op.create_foreign_key(None, 'treatment', 'phonebook', ['phonebook_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment', type_='foreignkey')
    op.drop_column('treatment', 'phonebook_id')
    # ### end Alembic commands ###
