"""update tratment status.

Revision ID: 9fa616bc2c95
Revises: f4994e932e9a
Create Date: 2025-05-26 16:26:00.963984

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fa616bc2c95"
down_revision: str | None = "f4994e932e9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "treatment_menu",
        "shop",
        ["shop_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "treatment_menu", type_="foreignkey")
    # ### end Alembic commands ###
