"""update treatment: fix duration

Revision ID: a49688e966f7
Revises: b0c61fedad62
Create Date: 2025-04-08 19:58:00.027011

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a49688e966f7"
down_revision: Union[str, None] = "b0c61fedad62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "treatment",
        sa.Column(
            "total_price", sa.Integer(), nullable=False, comment="총 실제 시술 가격"
        ),
    )
    op.drop_column("treatment_item", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "treatment_item",
        sa.Column(
            "price",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
            comment="시술 가격 (수정 가능)",
        ),
    )
    op.drop_column("treatment", "total_price")
    # ### end Alembic commands ###
