"""update shop_invite comment

Revision ID: a6c7166dbc9e
Revises: f800404fc982
Create Date: 2025-05-22 15:44:58.744363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6c7166dbc9e'
down_revision: Union[str, None] = 'f800404fc982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_invite', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='초대코드 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('shop_invite', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='샵 ID',
               existing_nullable=False)
    op.alter_column('shop_invite', 'invite_code',
               existing_type=mysql.VARCHAR(length=20),
               comment='초대코드',
               existing_nullable=False)
    op.alter_column('shop_invite', 'expired_at',
               existing_type=mysql.DATETIME(),
               comment='만료일시',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_invite', 'expired_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='만료일시',
               existing_nullable=False)
    op.alter_column('shop_invite', 'invite_code',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='초대코드',
               existing_nullable=False)
    op.alter_column('shop_invite', 'shop_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='샵 ID',
               existing_nullable=False)
    op.alter_column('shop_invite', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='초대코드 ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
