"""update treatment: fix duration

Revision ID: b0c61fedad62
Revises: 7dfe484d30d3
Create Date: 2025-04-08 19:54:49.894461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0c61fedad62'
down_revision: Union[str, None] = '7dfe484d30d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_item', 'name')
    op.drop_column('treatment_item', 'duration_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_item', sa.Column('duration_min', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='시술 시간 (수정 가능)'))
    op.add_column('treatment_item', sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='예약 시점의 시술명 (스냅샷)'))
    # ### end Alembic commands ###
