"""remove colum tretment_menu_detail: user_id

Revision ID: ca9537ba4378
Revises: f2574aa94f6c
Create Date: 2025-04-14 19:35:26.608498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca9537ba4378'
down_revision: Union[str, None] = 'f2574aa94f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phonebook', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='전화번호 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('phonebook', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='유저 ID',
               existing_nullable=False)
    op.alter_column('phonebook', 'group_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='그룹명 (선택)',
               existing_nullable=True)
    op.alter_column('phonebook', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='이름',
               existing_nullable=False)
    op.alter_column('phonebook', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               comment='전화번호',
               existing_nullable=False)
    op.alter_column('phonebook', 'memo',
               existing_type=mysql.TEXT(),
               comment='메모',
               existing_nullable=True)
    op.alter_column('phonebook', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('phonebook', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_table_comment(
        'phonebook',
        '전화번호부 테이블',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('treatment_menu_detail_ibfk_2', 'treatment_menu_detail', type_='foreignkey')
    op.drop_column('treatment_menu_detail', 'user_id')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment='비밀번호',
               existing_nullable=False)
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='유저 토큰',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_comment='유저 토큰',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='비밀번호',
               existing_nullable=False)
    op.add_column('treatment_menu_detail', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='유저 ID'))
    op.create_foreign_key('treatment_menu_detail_ibfk_2', 'treatment_menu_detail', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'phonebook',
        existing_comment='전화번호부 테이블',
        schema=None
    )
    op.alter_column('phonebook', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('phonebook', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('phonebook', 'memo',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='메모',
               existing_nullable=True)
    op.alter_column('phonebook', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='전화번호',
               existing_nullable=False)
    op.alter_column('phonebook', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='이름',
               existing_nullable=False)
    op.alter_column('phonebook', 'group_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='그룹명 (선택)',
               existing_nullable=True)
    op.alter_column('phonebook', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='유저 ID',
               existing_nullable=False)
    op.alter_column('phonebook', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='전화번호 ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
