"""update invite shop_id is uniq

Revision ID: d91be80d4079
Revises: 40e91ecbe21e
Create Date: 2025-05-22 17:21:40.472833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91be80d4079'
down_revision: Union[str, None] = '40e91ecbe21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shop_invite_shop_id', 'shop_invite', ['shop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shop_invite_shop_id', 'shop_invite', type_='unique')
    # ### end Alembic commands ###
