"""update user model: role

Revision ID: de63028212b5
Revises: 15f7b3415d60
Create Date: 2025-04-07 13:47:35.925933

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de63028212b5"
down_revision: Union[str, None] = "15f7b3415d60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MASTER", "MANAGER", name="userrole"),
            server_default="MASTER",
            nullable=False,
            comment="유저 권한",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
