"""update user model: add token m drop email

Revision ID: e0e3a7e4d114
Revises: 9f6c54addfeb
Create Date: 2025-03-19 03:23:55.625322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0e3a7e4d114"
down_revision: Union[str, None] = "9f6c54addfeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("token", sa.String(length=100), nullable=False, comment="유저 토큰"),
    )
    op.alter_column(
        "users",
        "name",
        existing_type=mysql.VARCHAR(length=50),
        comment="유저 이름",
        existing_nullable=False,
    )
    op.drop_index("email", table_name="users")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", mysql.VARCHAR(length=100), nullable=False)
    )
    op.create_index("email", "users", ["email"], unique=True)
    op.alter_column(
        "users",
        "name",
        existing_type=mysql.VARCHAR(length=50),
        comment=None,
        existing_comment="유저 이름",
        existing_nullable=False,
    )
    op.drop_column("users", "token")
    # ### end Alembic commands ###
