"""update user model: add email

Revision ID: eac98a1c782d
Revises: e0e3a7e4d114
Create Date: 2025-03-19 05:44:57.328588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eac98a1c782d'
down_revision: Union[str, None] = 'e0e3a7e4d114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False, comment='유저 이메일'))
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='유저 토큰')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='유저 토큰')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
