"""update treatment: add status and finished_at

Revision ID: f2574aa94f6c
Revises: a49688e966f7
Create Date: 2025-04-08 20:07:42.206413

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2574aa94f6c"
down_revision: Union[str, None] = "a49688e966f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "treatment",
        sa.Column(
            "status",
            sa.Enum(
                "RESERVED", "VISITED", "CANCELLED", "NO_SHOW", name="treatment_status"
            ),
            nullable=False,
            comment="예약 상태",
        ),
    )
    op.add_column(
        "treatment",
        sa.Column("finished_at", sa.DateTime(), nullable=True, comment="시술 완료일시"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("treatment", "finished_at")
    op.drop_column("treatment", "status")
    # ### end Alembic commands ###
