"""add coloum : treatment.payment_method

Revision ID: f4994e932e9a
Revises: 06223b763c27
Create Date: 2025-05-26 15:57:17.113634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4994e932e9a'
down_revision: Union[str, None] = '06223b763c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment', sa.Column('payment_method', sa.Enum('CARD', 'CASH', 'UNPAID', name='payment_method'), nullable=False, comment='결제 수단'))
    op.add_column('treatment', sa.Column('staff_user_id', sa.Integer(), nullable=True, comment='시술 담당자 유저 ID'))
    op.add_column('treatment', sa.Column('created_user_id', sa.Integer(), nullable=True, comment='예약 생성자 유저 ID'))
    op.create_foreign_key(None, 'treatment', 'users', ['staff_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'treatment', 'users', ['created_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment', type_='foreignkey')
    op.drop_constraint(None, 'treatment', type_='foreignkey')
    op.drop_column('treatment', 'created_user_id')
    op.drop_column('treatment', 'staff_user_id')
    op.drop_column('treatment', 'payment_method')
    # ### end Alembic commands ###
