"""create model shop_user

Revision ID: fa22b5296fc2
Revises: 0b6d99f6fb6b
Create Date: 2025-05-20 18:28:43.502402

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa22b5296fc2"
down_revision: Union[str, None] = "0b6d99f6fb6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="PK"),
        sa.Column("shop_id", sa.Integer(), nullable=False, comment="샵 ID"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="유저 ID"),
        sa.Column(
            "is_primary_owner",
            sa.Integer(),
            nullable=False,
            comment="대표 원장 여부 (1=대표, 0=아님)",
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shop.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shop_id", "user_id", name="uq_shop_user"),
        comment="샵-유저 매핑 테이블",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_user")
    # ### end Alembic commands ###
